[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.0"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_VERSION = "0.148.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -F -b $DEPLOY_PRIME_URL"
